kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: wordpress
  name: wordpress-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels: 
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress:latest
          ports:
            - containerPort: {{ .Values.ContainerPort }}
          env:
            - name: DB_NAME
              value: {{ .Values.DBName }}

---

kind: Service
apiVersion: v1
metadata:
  name: wordpress-service
spec:
  type: NodePort
  selector:
    app: wordpress
  ports:
    - port: 80
      targetPort: {{ .Values.ContainerPort }}